[Interface]
Address = 10.10.10.1/24
ListenPort = 51820
PrivateKey = <Server PivateKey>
    
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o ens33 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o ens33 -j MASQUERADE
    
[Peer]
# Client 1
PublicKey = <Client PublicKey> 
AllowedIPs = 10.10.10.2/32