[Interface]
PrivateKey = <Client Private Key>
Address = 10.10.10.2/24
DNS = <Server IP>
    
[Peer]
PublicKey = <Server Public Key>
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = <Server IP>:51820 
persistentKeepalive = 25