#!/usr/bin/nft -f

flush ruleset

define WG_IF = wg0
define EXT_IF = ens37

table inet filter {

        set ssh_step1 {
                typeof ip saddr
                flags timeout
        }

        set ssh_step2 {
                typeof ip saddr
                flags timeout
        }

        set ip_blacklist {
                typeof ip saddr
                flags timeout
        }

        chain ssh_guard {
                ip saddr @ssh_step2 add @ip_blacklist { ip saddr timeout 12h } drop
                ip saddr @ssh_step1 add @ssh_step2 { ip saddr timeout 10s } accept
                add @ssh_step1 { ip saddr timeout 10s } accept
        }

        chain forward {
                type filter hook forward priority 0;
                policy drop;

                ip saddr @ip_blacklist drop

                ct state established,related accept

                iifname $WG_IF oifname $EXT_IF accept
        }

        chain input {
                type filter hook input priority 0;
                policy drop

                ip saddr @ip_blacklist drop

                ct state established,related accept
                ct state invalid drop

                iifname lo accept

                ct state new udp dport 51820 accept

                iifname $WG_IF ct state new tcp dport 53 accept
                iifname $WG_IF ct state new udp dport 53 accept

                iifname $WG_IF ct state new tcp dport 22 jump ssh_guard
        }

        chain output {
                type filter hook output priority 0;
                policy drop;

                ct state established,related accept

                oifname lo accept

                ct state new tcp dport { 53, 80, 443 } accept
                ct state new udp dport 53 accept
        }

        chain nat {
                type nat hook postrouting priority srcnat;
                policy accept;

                iifname $WG_IF oifname $EXT_IF masquerade
        }
}